### ISSUE TITLE
go-language-fatal-error-all-goroutines-are-asleep-deadlock

### ISSUE THREAD

**Issue by idevorel** [realPy/hogosuru#142]
https://github.com/realPy/hogosuru/blob/ee8533a3b579978e160160fd61859aa80b6c1e89/promise/promise.go#L249

use with wg.Wait() no channels or select {}
https://stackoverflow.com/questions/26927479/go-language-fatal-error-all-goroutines-are-asleep-deadlock

**Comment by realPy** [comment]
that's not the root of the problem at all. The concern is that channels in general shouldn't be used in webassembly because it's not true parallel processing. So he should prefer the use of promises instead. For me this is not an issue but a javascript stack constraint. This is a specific case of using go in webassembly. Are you affected by this problem.
If your read the code of wg.Wait you can see it use semaphore and it will deadlock too in this specific situation.

**Comment by realPy** [comment]
I suggested to read the doc here https://hogosuru.v-ip.fr/guides/async-work-with-promise
I explain the "thread mechanical" of js and how to sync with promise.
My advice: In webasembly never use go channel except for the last line of "inifinite" waiting of code need by a wasm.

**Comment by idevorel** [comment]
I don't know why or how , but i get error and my app crash , with waiting with "channels" or "select{}".
just wg.Wait() work well for me.

**Comment by realPy** [comment]
And you are using Await?

**Comment by idevorel** [comment]
yes

**Comment by realPy** [comment]
You can make a pr if you want. I will integrate it.
